"""
Module: config.models.enums

Description:
    Centralized enumerations used throughout the Hi-Lo game platform.

Keeping enums in a single module prevents inconsistent string values
between models, schemas, services, controllers, repositories, and
adapters.

The enums defined here cover:

    - Operator lifecycle
    - Player lifecycle
    - Adapter lifecycle
    - Game lifecycle
    - Round lifecycle
    - Player prediction
    - Round result
    - Financial transactions
    - Transaction lifecycle
    - Wallet operations
    - Wallet operation lifecycle
    - Idempotency state

All values are persisted as strings in MongoDB and exposed through
API schemas where required.
"""

from enum import Enum


# ============================================================================
# OPERATOR
# ============================================================================


class OperatorStatus(str, Enum):
    """
    Status of an operator/casino integration.

    ACTIVE:
        Operator can use the game.

    INACTIVE:
        Operator integration is disabled.

    SUSPENDED:
        Operator integration is temporarily suspended.
    """

    ACTIVE = "active"
    INACTIVE = "inactive"
    SUSPENDED = "suspended"


# ============================================================================
# PLAYER
# ============================================================================


class PlayerStatus(str, Enum):
    """
    Status of a player within the game platform.

    ACTIVE:
        Player can play.

    INACTIVE:
        Player is temporarily inactive.

    BLOCKED:
        Player is not allowed to play.
    """

    ACTIVE = "active"
    INACTIVE = "inactive"
    BLOCKED = "blocked"


# ============================================================================
# ADAPTER
# ============================================================================


class AdapterType(str, Enum):
    """
    Supported wallet adapter implementations.

    MOCK:
        Local adapter used for development and testing.

    HTTP:
        Adapter used to communicate with an external operator
        wallet through HTTP APIs.
    """

    MOCK = "mock"
    HTTP = "http"


class AdapterStatus(str, Enum):
    """
    Lifecycle status of a wallet adapter configuration.
    """

    ACTIVE = "active"
    INACTIVE = "inactive"


# ============================================================================
# GAME
# ============================================================================


class GameStatus(str, Enum):
    """
    Lifecycle status of a Hi-Lo game session.

    ACTIVE:
        Game is currently playable.

    COMPLETED:
        Game has finished normally.

    CANCELLED:
        Game was explicitly cancelled.

    EXPIRED:
        Game was abandoned or exceeded its configured lifetime.
    """

    ACTIVE = "active"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    EXPIRED = "expired"


# ============================================================================
# ROUND
# ============================================================================


class RoundStatus(str, Enum):
    """
    Lifecycle status of an individual Hi-Lo round.

    PENDING:
        Round record has been created but processing has not started.

    ACTIVE:
        Player has placed the prediction and the round is being processed.

    WON:
        Player correctly predicted the result.

    LOST:
        Player prediction was incorrect.

    PUSH:
        Round resulted in an equal-card outcome and the configured
        equal-card rule resulted in a push.

    CANCELLED:
        Round was cancelled before normal completion.

    FAILED:
        Round processing failed due to a system or wallet error.
    """

    PENDING = "pending"
    ACTIVE = "active"
    WON = "won"
    LOST = "lost"
    PUSH = "push"
    CANCELLED = "cancelled"
    FAILED = "failed"


class Prediction(str, Enum):
    """
    Player prediction for the next card.
    """

    HIGHER = "higher"
    LOWER = "lower"


class RoundResult(str, Enum):
    """
    Result generated after comparing the predicted card with the
    revealed card.
    """

    WIN = "win"
    LOSS = "loss"
    PUSH = "push"


# ============================================================================
# TRANSACTIONS
# ============================================================================


class TransactionType(str, Enum):
    """
    Financial transaction types generated by the game.

    BET:
        Amount debited when the player places a bet.

    WIN:
        Winnings credited after a successful round.

    REFUND:
        Original bet returned to the player.

    ROLLBACK:
        Reversal of a previously processed financial transaction.

    CANCEL:
        Financial operation generated when a game/round is cancelled.

    ADJUSTMENT:
        Manual or system balance adjustment.
    """

    BET = "bet"
    WIN = "win"
    REFUND = "refund"
    ROLLBACK = "rollback"
    CANCEL = "cancel"
    ADJUSTMENT = "adjustment"


class TransactionStatus(str, Enum):
    """
    Lifecycle status of a financial transaction.

    PENDING:
        Transaction has been created but wallet processing has not
        completed.

    SUCCESS:
        Wallet operation completed successfully.

    FAILED:
        Wallet operation failed.

    REVERSED:
        Previously successful transaction was reversed.
    """

    PENDING = "pending"
    SUCCESS = "success"
    FAILED = "failed"
    REVERSED = "reversed"


# ============================================================================
# WALLET
# ============================================================================


class WalletOperationType(str, Enum):
    """
    Operations performed through an operator wallet adapter.

    BALANCE:
        Retrieve current player balance.

    DEBIT:
        Deduct money from the player's wallet.

    CREDIT:
        Add money to the player's wallet.

    ROLLBACK:
        Reverse a previous wallet operation.
    """

    BALANCE = "balance"
    DEBIT = "debit"
    CREDIT = "credit"
    ROLLBACK = "rollback"


class WalletOperationStatus(str, Enum):
    """
    Lifecycle status of a wallet operation.
    """

    PENDING = "pending"
    SUCCESS = "success"
    FAILED = "failed"


# ============================================================================
# IDEMPOTENCY
# ============================================================================


class IdempotencyStatus(str, Enum):
    """
    Processing state of an idempotent API request.

    PROCESSING:
        Request is currently being processed.

    COMPLETED:
        Request completed successfully.

    FAILED:
        Request processing failed.
    """

    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"