"""
Module: config.models.transaction_model

Description:
    Financial transaction persistence model and repository operations
    for the Hi-Lo platform.

Every financial event generated by the game must be persisted.

Examples:

    - BET
    - WIN
    - LOSS
    - REFUND
    - ROLLBACK
    - CANCEL
    - ADJUSTMENT

The transaction collection acts as the internal financial ledger
for the game platform.

Responsibilities:
    - Define the transaction persistence structure.
    - Create financial transaction records.
    - Retrieve transactions.
    - Update transaction status.
    - Retrieve transactions by game, round, player, and operator.
    - Support idempotent transaction processing.
    - Maintain references to external operator transactions.

Business logic must remain in the service layer.

This repository must NOT:
    - Calculate winnings.
    - Calculate payout amounts.
    - Call operator wallet APIs.
    - Select adapters.
    - Decide whether a transaction should be created.

Those responsibilities belong to:

    services/wallet/wallet_service.py
    services/wallet/transaction_service.py
    services/adapter/adapter_service.py
"""


from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Dict, List, Optional, Tuple

from bson import ObjectId
from bson.decimal128 import Decimal128
from pydantic import BaseModel, Field

from config.db_config import transaction_collection
from config.models.enums import (
    TransactionStatus,
    TransactionType,
)


# ============================================================================
# TRANSACTION MODEL
# ============================================================================


class TransactionModel(BaseModel):
    """
    Represents one financial event in the Hi-Lo platform.

    A transaction belongs to an operator and player and may optionally
    belong to a specific game and round.

    The model stores both the internal transaction identifier and the
    external transaction identifier returned by the operator/wallet
    integration.

    Attributes:
        id:
            Internal MongoDB document identifier.

        transaction_id:
            Unique internal transaction identifier.

        operator_id:
            Operator associated with the transaction.

        player_id:
            Player associated with the transaction.

        game_id:
            Optional game session identifier.

        round_id:
            Optional Hi-Lo round identifier.

        type:
            Type of financial transaction.

        status:
            Current transaction status.

        amount:
            Transaction amount.

        currency:
            Currency of the transaction.

        external_transaction_id:
            Transaction identifier supplied by the operator wallet.

        idempotency_key:
            Unique request key used to prevent duplicate financial
            transactions.

        parent_transaction_id:
            Reference to a previous transaction when this transaction
            is a refund, rollback, or reversal.

        adapter_id:
            Adapter used to communicate with the operator wallet.

        balance_before:
            Player balance before the transaction, when supplied by
            the operator.

        balance_after:
            Player balance after the transaction, when supplied by
            the operator.

        error_code:
            Normalized error code when the transaction fails.

        error_message:
            Safe error message when the transaction fails.

        metadata:
            Additional non-sensitive transaction metadata.

        created_at:
            Timestamp when the transaction record was created.

        completed_at:
            Timestamp when the transaction completed.

        updated_at:
            Timestamp when the transaction was last updated.
    """

    id: Optional[str] = None

    # ------------------------------------------------------------------------
    # IDENTIFICATION
    # ------------------------------------------------------------------------

    transaction_id: str = Field(
        ...,
        min_length=1,
        description="Unique internal transaction identifier.",
    )

    # ------------------------------------------------------------------------
    # OWNERSHIP / CONTEXT
    # ------------------------------------------------------------------------

    operator_id: str = Field(
        ...,
        min_length=1,
        description="Operator associated with the transaction.",
    )

    player_id: str = Field(
        ...,
        min_length=1,
        description="Player associated with the transaction.",
    )

    game_id: Optional[str] = Field(
        default=None,
        description="Optional Hi-Lo game identifier.",
    )

    round_id: Optional[str] = Field(
        default=None,
        description="Optional Hi-Lo round identifier.",
    )

    # ------------------------------------------------------------------------
    # TRANSACTION INFORMATION
    # ------------------------------------------------------------------------

    type: TransactionType = Field(
        ...,
        description="Financial transaction type.",
    )

    status: TransactionStatus = Field(
        default=TransactionStatus.PENDING,
        description="Current transaction status.",
    )

    amount: Decimal = Field(
        ...,
        ge=Decimal("0.00"),
        description="Financial transaction amount.",
    )

    currency: str = Field(
        ...,
        min_length=3,
        max_length=10,
        description="Currency used for the transaction.",
    )

    # ------------------------------------------------------------------------
    # OPERATOR TRANSACTION REFERENCES
    # ------------------------------------------------------------------------

    external_transaction_id: Optional[str] = Field(
        default=None,
        description="Transaction identifier returned by the operator.",
    )

    # ------------------------------------------------------------------------
    # IDEMPOTENCY
    # ------------------------------------------------------------------------

    idempotency_key: Optional[str] = Field(
        default=None,
        description="Unique key preventing duplicate transaction processing.",
    )

    # ------------------------------------------------------------------------
    # REVERSAL / ROLLBACK
    # ------------------------------------------------------------------------

    parent_transaction_id: Optional[str] = Field(
        default=None,
        description=(
            "Internal transaction ID of the transaction being "
            "refunded, rolled back, or reversed."
        ),
    )

    # ------------------------------------------------------------------------
    # ADAPTER
    # ------------------------------------------------------------------------

    adapter_id: Optional[str] = Field(
        default=None,
        description="Wallet adapter used for this transaction.",
    )

    # ------------------------------------------------------------------------
    # BALANCE SNAPSHOT
    # ------------------------------------------------------------------------

    balance_before: Optional[Decimal] = Field(
        default=None,
        ge=Decimal("0.00"),
        description="Player balance before the transaction.",
    )

    balance_after: Optional[Decimal] = Field(
        default=None,
        ge=Decimal("0.00"),
        description="Player balance after the transaction.",
    )

    # ------------------------------------------------------------------------
    # FAILURE INFORMATION
    # ------------------------------------------------------------------------

    error_code: Optional[str] = Field(
        default=None,
        description="Normalized transaction error code.",
    )

    error_message: Optional[str] = Field(
        default=None,
        description="Safe transaction failure message.",
    )

    # ------------------------------------------------------------------------
    # ADDITIONAL INFORMATION
    # ------------------------------------------------------------------------

    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional non-sensitive transaction metadata.",
    )

    # ------------------------------------------------------------------------
    # TIMESTAMPS
    # ------------------------------------------------------------------------

    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    completed_at: Optional[datetime] = None

    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


# ============================================================================
# TRANSACTION REPOSITORY
# ============================================================================


class TransactionRepository:
    """
    Repository responsible for financial transaction persistence.

    All MongoDB-specific transaction operations are maintained here.

    Business logic must remain outside this repository.
    """

    # ========================================================================
    # SERIALIZATION HELPERS
    # ========================================================================

    @staticmethod
    def _decimal_to_decimal128(
        value: Any,
    ) -> Any:
        """
        Convert Python Decimal to MongoDB Decimal128.

        Args:
            value:
                Value to convert.

        Returns:
            Decimal128 for Decimal values, otherwise the original value.
        """

        if isinstance(value, Decimal):
            return Decimal128(str(value))

        return value

    @classmethod
    def _prepare_value(
        cls,
        value: Any,
    ) -> Any:
        """
        Recursively prepare values for MongoDB persistence.

        Args:
            value:
                Value to prepare.

        Returns:
            MongoDB-compatible value.
        """

        if isinstance(value, Decimal):
            return Decimal128(str(value))

        if isinstance(value, dict):
            return {
                key: cls._prepare_value(item)
                for key, item in value.items()
            }

        if isinstance(value, list):
            return [
                cls._prepare_value(item)
                for item in value
            ]

        return value

    @classmethod
    def _prepare_for_mongo(
        cls,
        data: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Prepare transaction data for MongoDB.

        Args:
            data:
                Transaction data.

        Returns:
            MongoDB-compatible dictionary.
        """

        return {
            key: cls._prepare_value(value)
            for key, value in data.items()
        }

    @classmethod
    def _deserialize_value(
        cls,
        value: Any,
    ) -> Any:
        """
        Convert MongoDB-specific values into Python values.

        Args:
            value:
                MongoDB value.

        Returns:
            Python-compatible value.
        """

        if isinstance(value, Decimal128):
            return value.to_decimal()

        if isinstance(value, dict):
            return {
                key: cls._deserialize_value(item)
                for key, item in value.items()
            }

        if isinstance(value, list):
            return [
                cls._deserialize_value(item)
                for item in value
            ]

        return value

    @classmethod
    def _deserialize_document(
        cls,
        document: Optional[Dict[str, Any]],
    ) -> Optional[Dict[str, Any]]:
        """
        Convert a MongoDB transaction document into an application
        friendly dictionary.

        Args:
            document:
                MongoDB document.

        Returns:
            Deserialized transaction document or None.
        """

        if not document:
            return None

        document = cls._deserialize_value(
            document.copy()
        )

        if "_id" in document:
            document["id"] = str(
                document.pop("_id")
            )

        return document

    # ========================================================================
    # CREATE
    # ========================================================================

    @classmethod
    async def create(
        cls,
        data: Dict[str, Any],
    ) -> str:
        """
        Create a financial transaction record.

        Args:
            data:
                Transaction document.

        Returns:
            str:
                MongoDB identifier of the created transaction.
        """

        now = datetime.now(timezone.utc)

        data = data.copy()

        data.setdefault(
            "created_at",
            now,
        )

        data.setdefault(
            "updated_at",
            now,
        )

        data = cls._prepare_for_mongo(
            data
        )

        result = await transaction_collection.insert_one(
            data
        )

        return str(result.inserted_id)

    # ========================================================================
    # GET BY INTERNAL TRANSACTION ID
    # ========================================================================

    @classmethod
    async def get_by_id(
        cls,
        transaction_id: str,
    ) -> Optional[Dict[str, Any]]:
        """
        Retrieve a transaction using its internal transaction ID.

        Args:
            transaction_id:
                Internal transaction identifier.

        Returns:
            Transaction document if found, otherwise None.
        """

        document = await transaction_collection.find_one(
            {
                "transaction_id": transaction_id,
            }
        )

        return cls._deserialize_document(
            document
        )

    # ========================================================================
    # GET BY MONGODB ID
    # ========================================================================

    @classmethod
    async def get_by_object_id(
        cls,
        transaction_id: str,
    ) -> Optional[Dict[str, Any]]:
        """
        Retrieve a transaction using its MongoDB ObjectId.

        Args:
            transaction_id:
                MongoDB ObjectId represented as a string.

        Returns:
            Transaction document if found, otherwise None.
        """

        if not ObjectId.is_valid(transaction_id):
            return None

        document = await transaction_collection.find_one(
            {
                "_id": ObjectId(transaction_id),
            }
        )

        return cls._deserialize_document(
            document
        )

    # ========================================================================
    # GET BY EXTERNAL TRANSACTION ID
    # ========================================================================

    @classmethod
    async def get_by_external_id(
        cls,
        external_transaction_id: str,
        operator_id: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """
        Retrieve a transaction using the operator's transaction ID.

        Args:
            external_transaction_id:
                Operator-provided transaction identifier.

            operator_id:
                Optional operator identifier for additional isolation.

        Returns:
            Transaction document if found, otherwise None.
        """

        condition: Dict[str, Any] = {
            "external_transaction_id": external_transaction_id,
        }

        if operator_id:
            condition["operator_id"] = operator_id

        document = await transaction_collection.find_one(
            condition
        )

        return cls._deserialize_document(
            document
        )

    # ========================================================================
    # GET BY IDEMPOTENCY KEY
    # ========================================================================

    @classmethod
    async def get_by_idempotency_key(
        cls,
        idempotency_key: str,
        operator_id: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        """
        Retrieve an existing transaction using its idempotency key.

        This method is critical for preventing duplicate financial
        operations when the operator retries the same request.

        Args:
            idempotency_key:
                Unique request key.

            operator_id:
                Optional operator identifier.

        Returns:
            Existing transaction if found, otherwise None.
        """

        condition: Dict[str, Any] = {
            "idempotency_key": idempotency_key,
        }

        if operator_id:
            condition["operator_id"] = operator_id

        document = await transaction_collection.find_one(
            condition
        )

        return cls._deserialize_document(
            document
        )

    # ========================================================================
    # GET GAME TRANSACTIONS
    # ========================================================================

    @classmethod
    async def get_game_transactions(
        cls,
        game_id: str,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve all transactions belonging to a game.

        Args:
            game_id:
                Game identifier.

        Returns:
            List of transaction documents.
        """

        cursor = (
            transaction_collection
            .find(
                {
                    "game_id": game_id,
                }
            )
            .sort(
                "created_at",
                -1,
            )
        )

        documents = await cursor.to_list(
            length=None
        )

        return [
            cls._deserialize_document(document)
            for document in documents
        ]

    # ========================================================================
    # GET ROUND TRANSACTIONS
    # ========================================================================

    @classmethod
    async def get_round_transactions(
        cls,
        round_id: str,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve all financial transactions associated with a round.

        Args:
            round_id:
                Hi-Lo round identifier.

        Returns:
            List of transaction documents.
        """

        cursor = (
            transaction_collection
            .find(
                {
                    "round_id": round_id,
                }
            )
            .sort(
                "created_at",
                1,
            )
        )

        documents = await cursor.to_list(
            length=None
        )

        return [
            cls._deserialize_document(document)
            for document in documents
        ]

    # ========================================================================
    # GET PLAYER TRANSACTIONS
    # ========================================================================

    @classmethod
    async def get_player_transactions(
        cls,
        player_id: str,
        skip: int = 0,
        limit: int = 20,
    ) -> Tuple[List[Dict[str, Any]], int]:
        """
        Retrieve paginated transaction history for a player.

        Args:
            player_id:
                Player identifier.

            skip:
                Number of records to skip.

            limit:
                Maximum number of records.

        Returns:
            Tuple containing:
                - Transaction history.
                - Total transaction count.
        """

        condition = {
            "player_id": player_id,
        }

        cursor = (
            transaction_collection
            .find(condition)
            .sort(
                "created_at",
                -1,
            )
            .skip(skip)
            .limit(limit)
        )

        documents = await cursor.to_list(
            length=limit
        )

        total = await transaction_collection.count_documents(
            condition
        )

        transactions = [
            cls._deserialize_document(document)
            for document in documents
        ]

        return transactions, total

    # ========================================================================
    # GET OPERATOR TRANSACTIONS
    # ========================================================================

    @classmethod
    async def get_operator_transactions(
        cls,
        operator_id: str,
        skip: int = 0,
        limit: int = 20,
    ) -> Tuple[List[Dict[str, Any]], int]:
        """
        Retrieve paginated transactions for an operator.

        Args:
            operator_id:
                Operator identifier.

            skip:
                Number of records to skip.

            limit:
                Maximum number of records.

        Returns:
            Tuple containing:
                - Transaction history.
                - Total transaction count.
        """

        condition = {
            "operator_id": operator_id,
        }

        cursor = (
            transaction_collection
            .find(condition)
            .sort(
                "created_at",
                -1,
            )
            .skip(skip)
            .limit(limit)
        )

        documents = await cursor.to_list(
            length=limit
        )

        total = await transaction_collection.count_documents(
            condition
        )

        transactions = [
            cls._deserialize_document(document)
            for document in documents
        ]

        return transactions, total

    # ========================================================================
    # UPDATE
    # ========================================================================

    @classmethod
    async def update(
        cls,
        transaction_id: str,
        data: Dict[str, Any],
    ) -> bool:
        """
        Update a transaction.

        Args:
            transaction_id:
                Internal transaction identifier.

            data:
                Fields to update.

        Returns:
            True when the transaction was modified.
        """

        data = data.copy()

        data["updated_at"] = (
            datetime.now(timezone.utc)
        )

        data = cls._prepare_for_mongo(
            data
        )

        result = await transaction_collection.update_one(
            {
                "transaction_id": transaction_id,
            },
            {
                "$set": data,
            },
        )

        return result.modified_count > 0

    # ========================================================================
    # COMPLETE
    # ========================================================================

    @classmethod
    async def complete(
        cls,
        transaction_id: str,
        status: TransactionStatus,
        external_transaction_id: Optional[str] = None,
        balance_before: Optional[Decimal] = None,
        balance_after: Optional[Decimal] = None,
    ) -> bool:
        """
        Complete a financial transaction.

        Args:
            transaction_id:
                Internal transaction identifier.

            status:
                Final transaction status.

            external_transaction_id:
                Optional operator transaction identifier.

            balance_before:
                Optional balance before transaction.

            balance_after:
                Optional balance after transaction.

        Returns:
            True if the transaction was updated.
        """

        update_data: Dict[str, Any] = {
            "status": status.value,
            "completed_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        }

        if external_transaction_id:
            update_data[
                "external_transaction_id"
            ] = external_transaction_id

        if balance_before is not None:
            update_data[
                "balance_before"
            ] = balance_before

        if balance_after is not None:
            update_data[
                "balance_after"
            ] = balance_after

        update_data = cls._prepare_for_mongo(
            update_data
        )

        result = await transaction_collection.update_one(
            {
                "transaction_id": transaction_id,
            },
            {
                "$set": update_data,
            },
        )

        return result.modified_count > 0

    # ========================================================================
    # MARK FAILED
    # ========================================================================

    @classmethod
    async def mark_failed(
        cls,
        transaction_id: str,
        error_code: Optional[str] = None,
        error_message: Optional[str] = None,
    ) -> bool:
        """
        Mark a transaction as failed.

        Args:
            transaction_id:
                Internal transaction identifier.

            error_code:
                Optional normalized error code.

            error_message:
                Optional safe error message.

        Returns:
            True if the transaction was updated.
        """

        update_data: Dict[str, Any] = {
            "status": TransactionStatus.FAILED.value,
            "completed_at": datetime.now(timezone.utc),
            "updated_at": datetime.now(timezone.utc),
        }

        if error_code:
            update_data[
                "error_code"
            ] = error_code

        if error_message:
            update_data[
                "error_message"
            ] = error_message

        result = await transaction_collection.update_one(
            {
                "transaction_id": transaction_id,
            },
            {
                "$set": update_data,
            },
        )

        return result.modified_count > 0