"""
Module: schemas.transaction.transaction_schema

Description:
    Pydantic schemas for financial transaction APIs.

Transactions represent all wallet-affecting events generated by
the Hi-Lo game platform.

Examples:

    - BET
    - WIN
    - REFUND
    - ROLLBACK
    - CANCEL
    - ADJUSTMENT

The schemas intentionally do not expose sensitive wallet credentials.
"""

from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, Optional

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
)

from config.models.enums import (
    TransactionStatus,
    TransactionType,
)
from config.models.enums import (
    WalletOperationStatus,
)

# ============================================================================
# CREATE TRANSACTION
# ============================================================================


class TransactionCreateRequest(BaseModel):
    """
    Request schema for creating a financial transaction.

    In normal game flow this request is generated internally by the
    transaction service rather than directly by a frontend client.
    """

    operator_id: str = Field(
        ...,
        min_length=1,
    )

    player_id: str = Field(
        ...,
        min_length=1,
    )

    game_id: Optional[str] = None

    round_id: Optional[str] = None

    type: TransactionType

    amount: Decimal = Field(
        ...,
        gt=Decimal("0"),
    )

    currency: str = Field(
        ...,
        min_length=3,
        max_length=10,
    )

    idempotency_key: str = Field(
        ...,
        min_length=1,
        max_length=255,
    )

    metadata: Dict[str, Any] = Field(
        default_factory=dict,
    )


# ============================================================================
# TRANSACTION RESPONSE
# ============================================================================


class TransactionResponse(BaseModel):
    """
    Public transaction response.
    """

    model_config = ConfigDict(
        from_attributes=True,
    )

    id: Optional[str] = None

    transaction_id: str

    operator_id: str

    player_id: str

    game_id: Optional[str] = None

    round_id: Optional[str] = None

    type: TransactionType

    status: TransactionStatus

    amount: Decimal

    currency: str

    external_transaction_id: Optional[str] = None

    idempotency_key: Optional[str] = None

    parent_transaction_id: Optional[str] = None

    adapter_id: Optional[str] = None

    balance_before: Optional[Decimal] = None

    balance_after: Optional[Decimal] = None

    error_code: Optional[str] = None

    error_message: Optional[str] = None

    metadata: Dict[str, Any] = Field(
        default_factory=dict,
    )

    created_at: datetime

    completed_at: Optional[datetime] = None

    updated_at: datetime


# ============================================================================
# TRANSACTION HISTORY
# ============================================================================


class TransactionListResponse(BaseModel):
    """
    Paginated transaction history response.
    """

    transactions: list[TransactionResponse]

    total: int

    page: int

    limit: int

    total_pages: int


# ============================================================================
# WALLET OPERATION REQUEST
# ============================================================================


class WalletTransactionRequest(BaseModel):
    """
    Request used internally to perform a wallet operation.

    The request is passed from the transaction service to the wallet
    service and eventually to the configured operator adapter.
    """

    operator_id: str

    player_id: str

    game_id: Optional[str] = None

    round_id: Optional[str] = None

    transaction_id: str

    transaction_type: TransactionType

    amount: Decimal = Field(
        ...,
        gt=Decimal("0"),
    )

    currency: str

    idempotency_key: str

    parent_transaction_id: Optional[str] = None

    metadata: Dict[str, Any] = Field(
        default_factory=dict,
    )


# ============================================================================
# WALLET OPERATION RESPONSE
# ============================================================================


class WalletTransactionResponse(BaseModel):
    """
    Normalized wallet operation response.

    This response is independent of the operator's wallet API format.
    """

    success: bool

    transaction_id: str

    external_transaction_id: Optional[str] = None

    status: TransactionStatus

    balance_before: Optional[Decimal] = None

    balance_after: Optional[Decimal] = None

    error_code: Optional[str] = None

    error_message: Optional[str] = None

    metadata: Dict[str, Any] = Field(
        default_factory=dict,
    )


# ============================================================================
# TRANSACTION STATUS RESPONSE
# ============================================================================


class WalletTransactionResponse(BaseModel):
    """
    Normalized wallet operation response.

    This response is independent of the operator's wallet API format.
    """

    success: bool

    transaction_id: str

    external_transaction_id: Optional[str] = None

    status: WalletOperationStatus

    balance_before: Optional[Decimal] = None

    balance_after: Optional[Decimal] = None

    error_code: Optional[str] = None

    error_message: Optional[str] = None

    metadata: Dict[str, Any] = Field(
        default_factory=dict,
    )